IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers')
CREATE TABLE dwh.DimCustomers(
  CustomerSid int IDENTITY(1,1),
  CustomerId int NOT NULL,
  Customer nvarchar(101) NOT NULL,
  CustomerType varchar(6) NOT NULL,
  AccountNumber nvarchar(10),
  FirstName nvarchar(50),
  MiddleName nvarchar(50),
  LastName nvarchar(50),
  CustomerAddressCountry nvarchar(50),
  CustomerProvince nvarchar(50),
  Name nvarchar(50),
  CustomerCountry nvarchar(50),
  CONSTRAINT PK_DimCustomers PRIMARY KEY CLUSTERED (CustomerSid),
  CONSTRAINT BK_DimCustomers UNIQUE (CustomerId)
)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerSid')
ALTER TABLE dwh.DimCustomers ADD CustomerSid int


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerId')
ALTER TABLE dwh.DimCustomers ADD CustomerId int


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='Customer')
ALTER TABLE dwh.DimCustomers ADD Customer nvarchar(101)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerType')
ALTER TABLE dwh.DimCustomers ADD CustomerType varchar(6)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='AccountNumber')
ALTER TABLE dwh.DimCustomers ADD AccountNumber nvarchar(10)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='FirstName')
ALTER TABLE dwh.DimCustomers ADD FirstName nvarchar(50)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='MiddleName')
ALTER TABLE dwh.DimCustomers ADD MiddleName nvarchar(50)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='LastName')
ALTER TABLE dwh.DimCustomers ADD LastName nvarchar(50)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerAddressCountry')
ALTER TABLE dwh.DimCustomers ADD CustomerAddressCountry nvarchar(50)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerProvince')
ALTER TABLE dwh.DimCustomers ADD CustomerProvince nvarchar(50)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='Name')
ALTER TABLE dwh.DimCustomers ADD Name nvarchar(50)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerCountry')
ALTER TABLE dwh.DimCustomers ADD CustomerCountry nvarchar(50)


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerSid' AND IS_NULLABLE='YES')
ALTER TABLE dwh.DimCustomers ALTER COLUMN CustomerSid int NOT NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerId' AND IS_NULLABLE='YES')
ALTER TABLE dwh.DimCustomers ALTER COLUMN CustomerId int NOT NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='Customer' AND IS_NULLABLE='YES')
ALTER TABLE dwh.DimCustomers ALTER COLUMN Customer nvarchar(101) NOT NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerType' AND IS_NULLABLE='YES')
ALTER TABLE dwh.DimCustomers ALTER COLUMN CustomerType varchar(6) NOT NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='AccountNumber' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN AccountNumber nvarchar(10) NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='FirstName' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN FirstName nvarchar(50) NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='MiddleName' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN MiddleName nvarchar(50) NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='LastName' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN LastName nvarchar(50) NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerAddressCountry' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN CustomerAddressCountry nvarchar(50) NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerProvince' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN CustomerProvince nvarchar(50) NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='Name' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN Name nvarchar(50) NULL


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND COLUMN_NAME='CustomerCountry' AND IS_NULLABLE='NO')
ALTER TABLE dwh.DimCustomers ALTER COLUMN CustomerCountry nvarchar(50) NULL


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND CONSTRAINT_NAME='PK_DimCustomers')
ALTER TABLE dwh.DimCustomers ADD CONSTRAINT PK_DimCustomers PRIMARY KEY CLUSTERED (CustomerSid)


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA='dwh' AND TABLE_NAME='DimCustomers' AND CONSTRAINT_NAME='BK_DimCustomers')
ALTER TABLE dwh.DimCustomers ADD CONSTRAINT BK_DimCustomers UNIQUE (CustomerId)