/**
 * Migra el contenido de src/ a astro/src/content/docs/
 * - Copia todos los .md adaptando el frontmatter
 * - Copia assets de src/.vuepress/public/ a astro/public/
 */

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync, statSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, relative, extname, basename } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const srcDir = join(root, 'src');
const docsDir = join(root, 'astro/src/content/docs');
const publicSrc = join(root, 'src/.vuepress/public');
const publicDst = join(root, 'astro/public');

let stats = { copied: 0, homeConverted: 0, titleAdded: 0, skipped: 0 };

// --- Frontmatter helpers ---

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { fm: {}, body: content, raw: '' };
  return { raw: match[1], body: match[2] };
}

function extractH1(body) {
  const m = body.match(/^#\s+(.+)$/m);
  return m ? m[1].trim().replace(/\s*[❤️✅⭐🥇💧🛠️❇️\u2747\uFE0F]+\s*$/, '').trim() : null;
}

// Páginas home: true → splash de Starlight
function convertHomePage(raw, body) {
  // Extraer campos del frontmatter YAML simple
  const get = (key) => {
    const m = raw.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'));
    return m ? m[1].trim().replace(/^['"]|['"]$/g, '') : null;
  };
  const getMultiline = (key) => {
    // features: lista de objetos
    const startIdx = raw.indexOf(`${key}:`);
    if (startIdx === -1) return null;
    return raw.slice(startIdx);
  };

  const title = get('title') || 'Manual';
  const tagline = get('tagline');
  const actionText = get('actionText');
  const actionLink = get('actionLink');
  const heroImage = get('heroImage');

  let hero = '  tagline: ' + (tagline ? JSON.stringify(tagline) : '""');
  if (actionText && actionLink) {
    const link = actionLink.replace(/^\//, '');
    hero += `\n  actions:\n    - text: ${JSON.stringify(actionText.replace(' →', ''))}\n      link: /${link}\n      icon: right-arrow`;
  }
  if (heroImage) {
    hero += `\n  image:\n    file: ../../assets/${basename(heroImage)}`;
  }

  return `---\ntitle: ${JSON.stringify(title)}\ntemplate: splash\nhero:\n${hero}\n---\n`;
}

function migrateFrontmatter(content, filePath) {
  const { raw, body } = parseFrontmatter(content);
  if (raw === undefined) {
    // Sin frontmatter — añadir título desde H1
    const title = extractH1(content);
    if (title) {
      stats.titleAdded++;
      return `---\ntitle: ${JSON.stringify(title)}\n---\n${content}`;
    }
    return content;
  }

  // ¿Es página home?
  if (/^home:\s*true/m.test(raw)) {
    stats.homeConverted++;
    return convertHomePage(raw, body) + (body || '');
  }

  // Campos a conservar en Starlight
  const keepKeys = ['title', 'description', 'sidebar'];
  // Campos a descartar
  const dropKeys = ['home', 'heroImage', 'tagline', 'actionText', 'actionLink',
    'footer', 'features', 'SidebarGroup', 'Catalog', 'Autogenerated',
    'sidebarDepth', 'position'];

  // Reconstruir frontmatter limpio
  const lines = raw.split('\n');
  const kept = [];
  let skipBlock = false;
  for (const line of lines) {
    const key = line.match(/^(\w+):/)?.[1];
    if (key && dropKeys.includes(key)) { skipBlock = true; continue; }
    if (key && !dropKeys.includes(key)) { skipBlock = false; }
    if (skipBlock && (line.startsWith('  ') || line.startsWith('- '))) continue;
    if (!skipBlock) kept.push(line);
  }

  // Si no hay title, intentar añadirlo desde H1
  let fmLines = kept.filter(l => l.trim());
  if (!fmLines.some(l => /^title:/i.test(l))) {
    const title = extractH1(body || '');
    if (title) {
      fmLines = [`title: ${JSON.stringify(title)}`, ...fmLines];
      stats.titleAdded++;
    }
  }

  if (fmLines.length === 0) {
    // Sin frontmatter útil
    return body || content;
  }

  stats.copied++;
  return `---\n${fmLines.join('\n')}\n---\n${body || ''}`;
}

// --- Copiar archivos recursivamente ---

function copyDir(src, dst, transform = null) {
  mkdirSync(dst, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry);
    const dstPath = join(dst, entry);
    const stat = statSync(srcPath);
    if (stat.isDirectory()) {
      copyDir(srcPath, dstPath, transform);
    } else {
      if (transform && transform.test && transform.test(entry)) {
        const content = readFileSync(srcPath, 'utf8');
        const transformed = transform.fn(content, srcPath);
        writeFileSync(dstPath, transformed, 'utf8');
      } else {
        copyFileSync(srcPath, dstPath);
      }
    }
  }
}

// --- Main ---

// 1. Copiar .md de src/ → astro/src/content/docs/ (excluir .vuepress)
console.log('Copiando archivos markdown...');
function copyMdDir(src, dst) {
  mkdirSync(dst, { recursive: true });
  for (const entry of readdirSync(src)) {
    if (entry === '.vuepress') continue;
    const srcPath = join(src, entry);
    const dstPath = join(dst, entry);
    const stat = statSync(srcPath);
    if (stat.isDirectory()) {
      copyMdDir(srcPath, dstPath);
    } else if (entry.endsWith('.md')) {
      const content = readFileSync(srcPath, 'utf8');
      const migrated = migrateFrontmatter(content, srcPath);
      writeFileSync(dstPath, migrated, 'utf8');
    }
    // Ignorar otros archivos en src/ (no hay assets aquí)
  }
}
copyMdDir(srcDir, docsDir);

// 2. Copiar assets de src/.vuepress/public/ → astro/public/
console.log('Copiando assets...');
function copyPublic(src, dst) {
  if (!existsSync(src)) return;
  mkdirSync(dst, { recursive: true });
  for (const entry of readdirSync(src)) {
    if (entry === 'sidebar.json') continue; // no necesario en Astro
    const srcPath = join(src, entry);
    const dstPath = join(dst, entry);
    const stat = statSync(srcPath);
    if (stat.isDirectory()) {
      copyPublic(srcPath, dstPath);
    } else {
      copyFileSync(srcPath, dstPath);
    }
  }
}
copyPublic(publicSrc, publicDst);

console.log('\n✅ Migración de contenido completada');
console.log(`   Páginas copiadas: ${stats.copied}`);
console.log(`   Títulos añadidos desde H1: ${stats.titleAdded}`);
console.log(`   Páginas home→splash: ${stats.homeConverted}`);
